name: Infra + App CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod


env:
  RESOURCE_GROUP: 'ai-demo-sabari'    # ensure this RG exists or create in infra job
  LOCATION: 'eastus'
  APP_NAME: 'sabari-demo-api'        # must match infra parameters
  SLOT_NAME: 'staging'
  PARAMETERS_FILE: 'infra/parameters.prod.json'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    outputs:
      infra_status: ${{ steps.deploy-bicep.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          # If using OIDC, remove creds and use with: allow-no-subscriptions: true
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Bicep (if not present)
        run: az bicep install

      - name: Create resource group (if not exists)
        run: |
          az group create --name $RESOURCE_GROUP --location $LOCATION

      - name: Bicep What-If
        run: |
          az deployment group what-if \
            --resource-group $RESOURCE_GROUP \
            --template-file infra/main.bicep \
            --parameters @$PARAMETERS_FILE

      - id: deploy-bicep
        name: Deploy Bicep infra
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file infra/main.bicep \
            --parameters @$PARAMETERS_FILE

  build-and-deploy:
    needs: deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./TestWebAPIBicep/TestWebAPIBicep.csproj

      - name: Build
        run: dotnet build ./TestWebAPIBicep/TestWebAPIBicep.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./TestWebAPIBicep/TestWebAPIBicep.csproj -c Release -o ./publish

      - name: Create ZIP package
        run: zip -r release.zip ./publish

      - name: Login to Azure (again - job-level)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'production'   # or omit if no slots
          package: ./release.zip   
